#pragma once

const int NUM_OF_DESCRIPTOR_SETS = 1;
const int NUM_OF_DESCRIPTORS = 2;
#define DESCRIPTOR_SET_INDEX_MODEL_MATRIX_UBO 0
#define DESCRIPTOR_SET_INDEX_SCENE_MATRIX_UBO 0
#define DESCRIPTOR_SET_BINDING_MODEL_MATRIX_UBO 0
#define DESCRIPTOR_SET_BINDING_SCENE_MATRIX_UBO 1