name: build-M1-MacOS
on:
  push:
  workflow_call:
jobs:
  build-M1-MacOS:
    runs-on: macos-14
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Build Version Checker
        run: subprojects/version_checker/build.sh

      - name: Install Ninja
        run: brew install ninja

      - name: Cache vcpkg_installed
        uses: actions/cache@v2
        with:
          path: ./build_release/vcpkg_installed
          key: ${{ runner.os }}-${{ runner.arch }}-vcpkg-${{ hashFiles('./vcpkg.json', './core/ikura/vcpkg.json') }}

      - name: Build App Bundle
        run: utils/scripts/build_app_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ikulab-motion-viewer-m1-macos
          path: |
            ./build_release/*.dmg
